#!/bin/bash

declare -A uddir_isotb

uddir_isotb["UD_Italian-PoSTWITA"]="it_postwita"
uddir_isotb["UD_English-PUD"]="en_pud"
uddir_isotb["UD_Turkish-IMST"]="tr_imst"
uddir_isotb["UD_Japanese-PUD"]="ja_pud"
uddir_isotb["UD_Spanish-AnCora"]="es_ancora"
uddir_isotb["UD_Italian-ISDT"]="it_isdt"
uddir_isotb["UD_Japanese-GSD"]="ja_gsd"
uddir_isotb["UD_English-ParTUT"]="en_partut"
uddir_isotb["UD_Arabic-PADT"]="ar_padt"
uddir_isotb["UD_German-GSD"]="de_gsd"
uddir_isotb["UD_Turkish-PUD"]="tr_pud"
uddir_isotb["UD_English-GUM"]="en_gum"
uddir_isotb["UD_Arabic-PUD"]="ar_pud"
uddir_isotb["UD_English-LinES"]="en_lines"
uddir_isotb["UD_Danish-DDT"]="da_ddt"
uddir_isotb["UD_Czech-CAC"]="cs_cac"
uddir_isotb["UD_Czech-PDT"]="cs_pdt"
uddir_isotb["UD_Japanese-Modern"]="ja_modern"
uddir_isotb["UD_Italian-PUD"]="it_pud"
uddir_isotb["UD_Czech-PUD"]="cs_pud"
uddir_isotb["UD_English-EWT"]="en_ewt"
uddir_isotb["UD_Dutch-Alpino"]="nl_alpino"
uddir_isotb["UD_Dutch-LassySmall"]="nl_lassysmall"
uddir_isotb["UD_Czech-FicTree"]="cs_fictree"
uddir_isotb["UD_Italian-ParTUT"]="it_partut"
uddir_isotb["UD_Czech-CLTT"]="cs_cltt"
